name: "Release Binary"

on:
  push:
    branches:
      - feature/nexe

jobs:
  tagged-release:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    name: "Tagged Release"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: tar -czvf openbmclapi-${{ runner.os }}.tar.gz dist nginx package.json node_modules
      - run: |
          npm run build:sea
          tar -czvf openbmclapi-${{ runner.os }}-sea.tar.gz openbmclapi
      - uses: "actions/cache@v4"
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.nexe
          key: nexec-${{ runner.os }}-cache
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: false
#          files: |
#            openbmclapi-${{ runner.os }}.tar.gz
#            openbmclapi-${{ runner.os }}-sea.tar.gz



