name: "Release Binary"

on:
  push:
    branches:
      - feature/nexe

jobs:
  tagged-release:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: tar -czvf openbmclapi-${{ matrix.os }}.tar.gz dist nginx package.json node_modules
      - run: |
          npm run build:sea
          tar -czvf openbmclapi-${{ matrix.os }}-sea.tar.gz openbmclapi
      - uses: "actions/cache@v2"
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.nexe
          key: ${{ runner.os }}-release-${{ matrix.os }}
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: false
#          files: |
#            openbmclapi-${{ matrix.os }}.tar.gz
#            openbmclapi-${{ matrix.os }}-sea.tar.gz



